import type { Metadata } from "next";
import "@/styles/index.scss";
import Providers from "@/Providers";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<meta name="p:domain_verify" content="49e77a0c694cff6faad83780d1d45dff" />
			</head>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
